/**
 * donezo mock dataset — realistic personal work-memory data for the prototype.
 * Pure literal data; all dates are ISO yyyy-MM-dd (datetimes yyyy-MM-ddTHH:mm:00).
 * "Today" for this dataset is Saturday 2026-07-25.
 */
import type {
  ActivityEntry,
  InboxItem,
  NoteItem,
  Project,
  Reminder,
  TaskItem,
} from "./types";

export const PROJECTS: Project[] = [
  {
    id: "loom",
    name: "Loom",
    color: "blue",
    purpose:
      "Internal user/session management platform in Go. Owns auth for the internal tools fleet.",
    outcome:
      "v1.0 = boring, audited auth nobody thinks about. Near term: v0.9 ships with session lifecycle actually correct.",
    currentFocus:
      "v0.9 hardening — session lifecycle bugs, esp. sessions surviving user deletion.",
    nextAction:
      "Write failing TestDeleteUserRevokesSessions reproducing the stale-session bug (repro script: scripts/repro-stale-session.sh).",
    altNextActions: [
      "Productionize the orphan-session sweep job (312 orphans found in staging)",
      "Finish owner-check middleware prototype behind session_owner_check flag (draft PR #142)",
    ],
    status: "active",
    resumeContext:
      "Stale-session thread: DeleteUser removes the users row but never touches sessions/api_keys — user_id there is a plain uuid copy, no FK cascade. Plan agreed 7/21: tx cascade in DeleteUser + middleware owner check as belt-and-braces. rc1 tagged 7/17 with a known-issues note; v0.9.0 final is gated on this fix.",
    tags: ["go", "auth", "work"],
  },
  {
    id: "openops",
    name: "OpenOps",
    color: "green",
    purpose: "Ops automation and deployment tooling for the service fleet.",
    outcome:
      "Deploys are one command with a 99% success SLO; alerts only page for user-facing symptoms.",
    currentFocus:
      "Pipeline reliability and alert quality. Runner-02 conntrack RCA writeup outstanding.",
    nextAction:
      "Write the runner-02 conntrack RCA doc — raw notes are in the 'Runner-02 conntrack RCA notes' note.",
    altNextActions: [
      "Draft canary-stage rollout plan for the top 3 services",
      "Finish the weekly deploy report automation",
    ],
    status: "active",
    resumeContext:
      "The health-gate deploy flake was nf_conntrack table exhaustion on ops-runner-02 — parallel smoke tests blew past the default max and dropped packets looked like gate timeouts. Raised nf_conntrack_max 7/21, runner back in pool, 40+ green runs since. Friday 15:00+ deploy freeze agreed 7/23.",
    tags: ["ops", "ci", "work"],
  },
  {
    id: "home-infra",
    name: "Home Infrastructure",
    color: "tan",
    purpose:
      "Home lab that runs itself: Puppet-managed, MAAS-provisioned, LXD cluster, segmented VLANs, verified backups. Weekend-cadence project.",
    outcome:
      "Any box can die on a Tuesday and nothing important is lost; rebuilds are hands-off via MAAS + Puppet.",
    currentFocus:
      "pve-01 PSU replacement, plus PAT hygiene after the 7/19 Puppet token expiry burned ~2h.",
    nextAction: "Install the bench-tested PSU in pve-01 and run burn-in (Sat 8/1).",
    altNextActions: [
      "Rotate the remaining service PATs and add expiry alerts for each",
      "Eval MAAS 3.6 — release notes hint at a fix for the IPMI power-query timeouts",
    ],
    status: "active",
    resumeContext:
      "pve-01 has been on a temp PSU from the retired chassis since 7/11; replacement arrived and bench-tested 7/25. Puppet PAT rotated 7/19 and now lives in hiera-eyaml; expiry reminder set. LXD cluster (lxd-01..03) has carried all containers since 6/13.",
    tags: ["homelab", "puppet", "lxd"],
  },
  {
    id: "5g-testbed",
    name: "5G Testbed",
    color: "violet",
    purpose:
      "Private 5G lab: RAN550 + srsRAN + Open5GS for realistic RAN/core testing without touching production spectrum.",
    outcome:
      "Two-cell setup doing repeatable attach/handover runs under scripted attenuation.",
    currentFocus:
      "Blocked on vendor licensing for the second cell. Keeping core configs and test scripts warm meanwhile.",
    nextAction:
      "Email Dan a nudge with a decision deadline — quote requested 6/12, chased 6/26, still nothing.",
    altNextActions: [
      "Extend the pytest attach smoke suite to record throughput per run",
      "Dry-run the two-cell config in ZMQ sim while the hardware is license-gated",
    ],
    status: "waiting",
    waitingOn: "Dan — RAN550 licensing quote",
    resumeContext:
      "Single-cell end-to-end works: UE attaches through 60 dB of pads, ~89 Mbps down. Second cell + handover work is gated on the RAN550 license SKU. RF bench is cabled per the rack wiring note; test SIMs are PLMN 999/70.",
    tags: ["5g", "srsran", "open5gs"],
  },
  {
    id: "personal-website",
    name: "Personal Website",
    color: "rose",
    purpose: "grewelltech.com refresh — make the site reflect actual current work.",
    outcome: "New Astro site live with the 4 ported posts plus the homelab writeup.",
    currentFocus: "None — parked since 5/8.",
    nextAction:
      "Finish the homelab writeup draft (content/posts/homelab.md — it stops mid-section 3, LXD migration).",
    altNextActions: [
      "Just ship the ported posts without the new writeup",
      "Timebox 2h: keep the starter template as-is and deploy",
    ],
    status: "paused",
    resumeContext:
      "Astro spike lives in ~/repos/site-next and already deploys to a Cloudflare Pages preview. Old Hugo site is still live. The writeup stalls at the LXD migration section; the rest of the outline is in the file.",
    tags: ["web", "writing", "personal"],
  },
  {
    id: "ai-research",
    name: "AI Assistant Research",
    color: "orange",
    purpose:
      "Stay sharp on local RAG, MCP servers, and agent evaluation; feed useful bits back into my own tooling.",
    outcome:
      "Working local RAG over my notes plus an MCP server I actually use daily.",
    currentFocus:
      "Turning the RAG spike into a clean Go+sqlite repo; eval harness sits at 34/40.",
    nextAction: "Write up the RAG eval results while the 6 failure cases are fresh.",
    altNextActions: [
      "Prototype an MCP server over donezo data",
      "Chase the 6 failing eval questions — all multi-hop",
    ],
    status: "active",
    resumeContext:
      "Stack: sqlite-vec + bge-m3, heading-aware chunking. Eval harness is 40 QA pairs over my notes, 34 pass; every failure is multi-hop. Code is moving from ~/spikes/rag into ~/repos/notes-rag.",
    tags: ["ai", "rag", "mcp"],
  },
  {
    id: "iso-kit",
    name: "ISO Kit",
    color: "steel",
    purpose:
      "Go tool to build and validate ISO 9660 images (Rock Ridge, El Torito, hybrid MBR/GPT) for MAAS and lab image work.",
    outcome: "Shipped — v1.0.0 tagged 2026-04-17; builds the MAAS ephemeral image reproducibly.",
    currentFocus: "None — wound down after 1.0.",
    nextAction: "Nothing planned. Reopen only if a MAAS image regression bites.",
    altNextActions: [],
    status: "completed",
    resumeContext:
      "Pure Go by design, no shelling out to xorriso. Fuzz corpus lives in test/fuzz; the release checklist note covers tag/build steps if a 1.0.1 is ever needed.",
    tags: ["go", "iso9660", "tooling"],
  },
];

export const ACTIVITIES: ActivityEntry[] = [
  // ── Loom ────────────────────────────────────────────────────────────────
  {
    id: "act-001",
    projectId: "loom",
    date: "2026-03-03",
    type: "work",
    title: "Backlog triage for v0.9 hardening cycle",
    details:
      "Went through 41 open issues, tagged 14 as v0.9-hardening. Session lifecycle and auth middleware dominate the list.",
    effortHours: 1.5,
    source: "manual",
    tags: ["planning"],
    links: [],
    nextAction: "Start with the session store refactor — everything else builds on it",
  },
  {
    id: "act-002",
    projectId: "loom",
    date: "2026-03-10",
    type: "work",
    title: "Refactor session store behind SessionStore interface",
    details:
      "Extracted SessionStore with memory and postgres implementations. Handlers no longer import pgx directly.",
    effortHours: 4,
    source: "manual",
    tags: ["go", "refactor"],
    links: [{ label: "PR #121", url: "https://github.com/grewelltech/loom/pull/121" }],
    nextAction: "Point the TTL sweeper at the new interface next",
  },
  {
    id: "act-003",
    projectId: "loom",
    date: "2026-03-12",
    type: "decision",
    title: "Decision: sessions stay in Postgres, no Redis",
    details:
      "Benchmarked lookup at 10k active sessions: p99 1.8 ms straight from Postgres. Redis would add an operational dependency for nothing at our scale. Revisit only past ~100k sessions.",
    effortHours: 2,
    source: "manual",
    tags: ["decision", "sessions"],
    links: [],
  },
  {
    id: "act-004",
    projectId: "loom",
    date: "2026-03-19",
    type: "work",
    title: "Fix token refresh race in auth middleware",
    details:
      "Concurrent requests could double-refresh and invalidate each other. Wrapped refresh in singleflight keyed by session id.",
    effortHours: 3,
    source: "manual",
    tags: ["bug", "concurrency"],
    links: [{ label: "PR #128", url: "https://github.com/grewelltech/loom/pull/128" }],
  },
  {
    id: "act-005",
    projectId: "loom",
    date: "2026-03-24",
    type: "work",
    title: "Rewrite session TTL sweeper as background ticker",
    details:
      "Replaced the external cron sweep with an in-process ticker, batch-deleting 500 rows per tx. No more thundering herd at :00.",
    effortHours: 3.5,
    source: "manual",
    tags: ["sessions", "go"],
    links: [],
    nextAction: "Watch sweep timing metrics for a week before closing this out",
  },
  {
    id: "act-006",
    projectId: "loom",
    date: "2026-03-31",
    type: "work",
    title: "Bump to Go 1.24, clear new vet warnings",
    details: "Toolchain bump plus three loopvar-adjacent fixes vet flagged in handler tests.",
    effortHours: 1.5,
    source: "manual",
    tags: ["chore", "go"],
    links: [],
  },
  {
    id: "act-007",
    projectId: "loom",
    date: "2026-04-07",
    type: "work",
    title: "Audit log for login/logout/admin events",
    details:
      "New audit_events table plus middleware hook. Admin actions record actor, target, and request id.",
    effortHours: 3,
    source: "manual",
    tags: ["audit", "security"],
    links: [],
  },
  {
    id: "act-008",
    projectId: "loom",
    date: "2026-04-09",
    type: "work",
    title: "Harden password reset flow",
    details:
      "Reset tokens are now single-use with a 15-minute expiry, and reset invalidates all other active sessions for the account.",
    effortHours: 2.5,
    source: "manual",
    tags: ["security"],
    links: [],
    nextAction: "Load test the login path before v0.8 tag",
  },
  {
    id: "act-009",
    projectId: "loom",
    date: "2026-04-16",
    type: "milestone",
    title: "Loom v0.8.0 released",
    details:
      "Tagged and deployed to the internal fleet. Headline items: audit log, hardened reset flow, session sweeper rewrite.",
    effortHours: 2,
    source: "manual",
    tags: ["release"],
    links: [],
  },
  {
    id: "act-010",
    projectId: "loom",
    date: "2026-04-23",
    type: "work",
    title: "Load test: sustained 500 rps logins",
    details:
      "k6 scripts against staging. Found pgx pool exhaustion at 40 conns under burst; bumped pool to 80 and added acquire-timeout metrics.",
    effortHours: 3,
    source: "manual",
    tags: ["perf", "k6"],
    links: [],
    nextAction: "Re-run k6 after the pool bump to confirm headroom",
  },
  {
    id: "act-011",
    projectId: "loom",
    date: "2026-04-28",
    type: "decision",
    title: "Decision: argon2id over bcrypt for new hashes",
    details:
      "argon2id with 64 MB / 3 iters clears OWASP guidance and costs ~45 ms on our nodes. Existing bcrypt hashes migrate transparently on next successful login.",
    effortHours: 1.5,
    source: "manual",
    tags: ["decision", "security"],
    links: [],
  },
  {
    id: "act-012",
    projectId: "loom",
    date: "2026-04-30",
    type: "work",
    title: "Implement argon2id migration on login",
    details:
      "Rehash-on-verify path with a hash_scheme column. Rollout is a no-op for users until they next log in.",
    effortHours: 4,
    source: "manual",
    tags: ["security", "migration"],
    links: [{ label: "PR #134", url: "https://github.com/grewelltech/loom/pull/134" }],
  },
  {
    id: "act-013",
    projectId: "loom",
    date: "2026-05-05",
    type: "work",
    title: "Session fixation review",
    details:
      "Walked the login path for fixation issues: session id rotates on privilege change and on login. Added a regression test for the rotate-on-login case.",
    effortHours: 2,
    source: "manual",
    tags: ["security", "sessions"],
    links: [],
  },
  {
    id: "act-014",
    projectId: "loom",
    date: "2026-05-12",
    type: "work",
    title: "Admin API: bulk user import",
    details:
      "CSV upload endpoint with dry-run mode. Validation report lists per-row errors before anything commits.",
    effortHours: 3.5,
    source: "manual",
    tags: ["api", "admin"],
    links: [],
  },
  {
    id: "act-015",
    projectId: "loom",
    date: "2026-05-14",
    type: "work",
    title: "CSV import edge cases: BOM, CRLF, dupe emails",
    details:
      "Excel exports start with a UTF-8 BOM that broke header matching. Also dedupe by normalized email with a clear per-row error.",
    effortHours: 2,
    source: "manual",
    tags: ["bug", "api"],
    links: [],
  },
  {
    id: "act-016",
    projectId: "loom",
    date: "2026-05-21",
    type: "research",
    title: "SCIM 2.0 provisioning read-through",
    details:
      "Read RFC 7643/7644 and two Go implementations. Big surface area for marginal value right now.",
    effortHours: 1.5,
    source: "manual",
    tags: ["scim", "reading"],
    links: [],
    nextAction: "Bring a cut/keep recommendation to v0.9 scoping",
  },
  {
    id: "act-017",
    projectId: "loom",
    date: "2026-05-28",
    type: "work",
    title: "Rate limiting on auth endpoints",
    details:
      "Token bucket keyed by IP+account on /login and /reset. Limits picked from the April load-test numbers.",
    effortHours: 3,
    source: "manual",
    tags: ["security", "api"],
    links: [],
  },
  {
    id: "act-018",
    projectId: "loom",
    date: "2026-06-03",
    type: "work",
    title: "OpenTelemetry traces for auth paths",
    details:
      "Spans across middleware, session store, and hashers. Login p99 breaks down as 45 ms hash + 2 ms store, as expected.",
    effortHours: 3,
    source: "manual",
    tags: ["observability"],
    links: [],
    nextAction: "Grafana panel for the login span breakdown",
  },
  {
    id: "act-019",
    projectId: "loom",
    date: "2026-06-09",
    type: "work",
    title: "Deflake TestSessionExpiry with injected clock",
    details:
      "Test slept real time and flaked on loaded CI runners. Introduced a Clock interface and drove expiry deterministically.",
    effortHours: 2,
    source: "manual",
    tags: ["tests", "flake"],
    links: [],
  },
  {
    id: "act-020",
    projectId: "loom",
    date: "2026-06-11",
    type: "work",
    title: "GC pause spike traced to session serialization",
    details:
      "Noticed 12 ms GC pauses in staging traces. Session JSON round-trips allocated per request; switched to pooled buffers, pauses back under 2 ms.",
    effortHours: 3.5,
    source: "capture",
    tags: ["perf", "go"],
    links: [],
  },
  {
    id: "act-021",
    projectId: "loom",
    date: "2026-06-17",
    type: "decision",
    title: "Decision: cut SCIM from v0.9",
    details:
      "Nobody upstream is asking for it yet and the hardening list is long. Deferred to v1.x; May read-through notes are enough to restart.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "scope"],
    links: [],
  },
  {
    id: "act-022",
    projectId: "loom",
    date: "2026-06-23",
    type: "work",
    title: "Partial index on sessions.expires_at",
    details:
      "Sweeper scans were seq-scanning as the table grew. Added a partial index WHERE revoked = false; sweep dropped from 900 ms to 40 ms.",
    effortHours: 2,
    source: "manual",
    tags: ["postgres", "perf"],
    links: [],
    nextAction: "Check prod sweep timing after the next deploy",
  },
  {
    id: "act-023",
    projectId: "loom",
    date: "2026-06-25",
    type: "work",
    title: "Refresh token rotation",
    details:
      "One-time-use refresh tokens with reuse detection — reuse revokes the whole session family.",
    effortHours: 4,
    source: "manual",
    tags: ["security", "sessions"],
    links: [{ label: "PR #137", url: "https://github.com/grewelltech/loom/pull/137" }],
  },
  {
    id: "act-024",
    projectId: "loom",
    date: "2026-07-01",
    type: "work",
    title: "Draft v0.9 release checklist",
    details:
      "Checklist covers migration order (argon2id column, session index), flag defaults, and rollback steps.",
    effortHours: 1.5,
    source: "manual",
    tags: ["release", "planning"],
    links: [],
    nextAction: "Walk the checklist against staging before rc1",
  },
  {
    id: "act-025",
    projectId: "loom",
    date: "2026-07-08",
    type: "work",
    title: "Fix panic on malformed JWT kid header",
    details:
      "A non-string kid claim hit a type assertion in the keyfunc and panicked the handler. Now a clean 401; added fuzz seed for the parser.",
    effortHours: 2,
    source: "manual",
    tags: ["bug", "jwt"],
    links: [{ label: "PR #139", url: "https://github.com/grewelltech/loom/pull/139" }],
  },
  {
    id: "act-026",
    projectId: "loom",
    date: "2026-07-09",
    type: "work",
    title: "pgx v5.6 upgrade plus pool metrics",
    details:
      "Routine bump; exposed AcquireCount/EmptyAcquireCount as Prometheus gauges while in there.",
    effortHours: 2,
    source: "manual",
    tags: ["chore", "postgres"],
    links: [],
  },
  {
    id: "act-027",
    projectId: "loom",
    date: "2026-07-13",
    type: "work",
    title: "Stale session reported after user deletion",
    details:
      "Support ping: deleted user u-4821 still shows an active session in the admin UI. Confirmed in staging — the sessions row survives the user delete and still validates.",
    effortHours: 2,
    source: "capture",
    tags: ["bug", "sessions"],
    links: [],
    nextAction: "Trace the DeleteUser path in user_service.go",
  },
  {
    id: "act-028",
    projectId: "loom",
    date: "2026-07-14",
    type: "work",
    title: "Traced DeleteUser: sessions never cleaned up",
    details:
      "DeleteUser removes the users row and writes audit, but never touches sessions. sessions.user_id is a plain uuid copy with no FK cascade, so nothing downstream fires.",
    effortHours: 2.5,
    source: "manual",
    tags: ["bug", "sessions"],
    links: [],
  },
  {
    id: "act-029",
    projectId: "loom",
    date: "2026-07-15",
    type: "work",
    title: "Repro stale session bug in dev",
    details:
      "Scripted it: create user, login, delete user — session survives and authenticates until TTL expiry. Script saved as scripts/repro-stale-session.sh.",
    effortHours: 1.5,
    source: "manual",
    tags: ["bug", "sessions"],
    links: [],
    nextAction: "Audit the other delete paths for the same gap",
  },
  {
    id: "act-030",
    projectId: "loom",
    date: "2026-07-15",
    type: "work",
    title: "Audit cascade paths: api_keys affected too",
    details:
      "api_keys has the same plain user_id copy and survives deletion. Password reset tokens are fine — that table has a real FK with ON DELETE CASCADE.",
    effortHours: 2,
    source: "manual",
    tags: ["bug", "audit"],
    links: [],
  },
  {
    id: "act-031",
    projectId: "loom",
    date: "2026-07-16",
    type: "work",
    title: "Wrote rc1 known-issues note for stale sessions",
    details:
      "Documented the bug, blast radius (sessions + api_keys), and the interim mitigation of manually revoking on offboard.",
    effortHours: 1,
    source: "manual",
    tags: ["release", "docs"],
    links: [],
    nextAction: "Tag rc1 tomorrow morning before standup",
  },
  {
    id: "act-032",
    projectId: "loom",
    date: "2026-07-17",
    type: "milestone",
    title: "Loom v0.9.0-rc1 tagged",
    details:
      "rc1 cut with the stale-session bug listed as a known issue. Final is gated on the fix landing.",
    effortHours: 1,
    source: "manual",
    tags: ["release"],
    links: [
      {
        label: "rc1 release notes",
        url: "https://wiki.internal.grewelltech.com/loom/v0.9.0-rc1",
      },
    ],
  },
  {
    id: "act-033",
    projectId: "loom",
    date: "2026-07-20",
    type: "work",
    title: "Counter for orphan-session lookups",
    details:
      "Added loom_session_orphan_lookups — sessions whose user_id no longer resolves. Staging shows ~27 hits/day, so this is live traffic, not just theory.",
    effortHours: 2,
    source: "manual",
    tags: ["observability", "sessions"],
    links: [
      {
        label: "Grafana: session health",
        url: "https://grafana.internal.grewelltech.com/d/loom-sessions",
      },
    ],
    nextAction: "Check the prod counter once v0.9 ships",
  },
  {
    id: "act-034",
    projectId: "loom",
    date: "2026-07-21",
    type: "work",
    title: "Repro stale session end-to-end in staging",
    details:
      "Ran the full flow via the admin UI against staging, not just the script. Same result: deleted user, live session, valid API responses.",
    effortHours: 1.5,
    source: "manual",
    tags: ["bug", "sessions"],
    links: [],
  },
  {
    id: "act-035",
    projectId: "loom",
    date: "2026-07-21",
    type: "work",
    title: "Quantified orphans: 312 stale sessions in staging",
    details:
      "One-off query joining sessions against users found 312 orphans dating back to January. Confirms this predates v0.8.",
    effortHours: 1.5,
    source: "manual",
    tags: ["sessions", "data"],
    links: [],
  },
  {
    id: "act-036",
    projectId: "loom",
    date: "2026-07-21",
    type: "decision",
    title: "Decision: fix = tx cascade + middleware owner check",
    details:
      "DeleteUser will delete sessions/api_keys in the same transaction, and middleware gets an owner-existence check behind session_owner_check as belt-and-braces. FK cascade alone can't cover the api_keys copy without a risky schema change mid-cycle.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "sessions"],
    links: [],
    nextAction: "Write the failing test first, then the tx change",
  },
  {
    id: "act-037",
    projectId: "loom",
    date: "2026-07-21",
    type: "meeting",
    title: "Walked Sam through stale-session findings",
    details:
      "20 minutes over the orphan numbers and the fix plan. Sam will handle the offboarding-runbook mitigation until the fix ships.",
    effortHours: 0.5,
    source: "manual",
    tags: ["sync"],
    links: [],
  },
  {
    id: "act-038",
    projectId: "loom",
    date: "2026-07-22",
    type: "work",
    title: "Owner-check middleware prototype behind flag",
    details:
      "Spike of the session_owner_check path with a small LRU so it's not a per-request DB hit. Draft PR up, not merged.",
    effortHours: 2.5,
    source: "manual",
    tags: ["sessions", "go"],
    links: [{ label: "Draft PR #142", url: "https://github.com/grewelltech/loom/pull/142" }],
  },
  {
    id: "act-039",
    projectId: "loom",
    date: "2026-07-23",
    type: "work",
    title: "Sweep job design: batch-revoke orphaned sessions",
    details:
      "Design for a one-off job to clear the existing 312 (and prod's unknown count): batches of 200, audit row per revocation, dry-run mode first.",
    effortHours: 1.5,
    source: "manual",
    tags: ["sessions", "design"],
    links: [],
  },
  {
    id: "act-040",
    projectId: "loom",
    date: "2026-07-24",
    type: "work",
    title: "Cleaned repro script, ready to become a failing test",
    details:
      "repro-stale-session.sh now sets up and tears down its own fixtures. Next step is porting it to TestDeleteUserRevokesSessions in session_service_test.go.",
    effortHours: 1,
    source: "manual",
    tags: ["tests", "sessions"],
    links: [],
    nextAction: "Write failing TestDeleteUserRevokesSessions Monday morning",
  },

  // ── OpenOps ─────────────────────────────────────────────────────────────
  {
    id: "act-041",
    projectId: "openops",
    date: "2026-03-04",
    type: "work",
    title: "Typed YAML schema for deploy configs",
    details:
      "Replaced free-form deploy.yml with a versioned schema plus a validate subcommand. Caught 9 latent config errors across services on first run.",
    effortHours: 3,
    source: "manual",
    tags: ["config", "dx"],
    links: [],
  },
  {
    id: "act-042",
    projectId: "openops",
    date: "2026-03-06",
    type: "meeting",
    title: "Ops sync: alert severity tiers agreed",
    details:
      "Three tiers — page, ticket, log. Anything that pages must map to a user-facing symptom.",
    effortHours: 1,
    source: "manual",
    tags: ["alerting", "sync"],
    links: [],
  },
  {
    id: "act-043",
    projectId: "openops",
    date: "2026-03-11",
    type: "work",
    title: "Retry with backoff on artifact upload step",
    details:
      "Uploads to the artifact store failed on transient 503s and killed whole runs. Three retries with jittered backoff; failures since: zero.",
    effortHours: 2,
    source: "manual",
    tags: ["ci", "reliability"],
    links: [],
    nextAction: "Watch that retries don't mask real failures in the weekly report",
  },
  {
    id: "act-044",
    projectId: "openops",
    date: "2026-03-18",
    type: "work",
    title: "Go module cache in pipeline: builds 6m to 2m",
    details:
      "Keyed cache on go.sum hash. Cold-cache path still correct — verified by nuking the cache and re-running.",
    effortHours: 2.5,
    source: "manual",
    tags: ["ci", "perf"],
    links: [],
  },
  {
    id: "act-045",
    projectId: "openops",
    date: "2026-03-25",
    type: "work",
    title: "Alertmanager route consolidation: 14 routes to 5",
    details:
      "Collapsed per-service routes into label-driven ones, dedupe by service. Config went from 400 lines to 120.",
    effortHours: 2,
    source: "manual",
    tags: ["alerting"],
    links: [],
  },
  {
    id: "act-046",
    projectId: "openops",
    date: "2026-03-27",
    type: "work",
    title: "Rollback runbook v2",
    details:
      "Rewrote around the new pipeline: one command per scenario, verified each on staging while writing.",
    effortHours: 1.5,
    source: "manual",
    tags: ["runbook", "docs"],
    links: [
      {
        label: "Runbook: rollback v2",
        url: "https://wiki.internal.grewelltech.com/ops/rollback-v2",
      },
    ],
  },
  {
    id: "act-047",
    projectId: "openops",
    date: "2026-04-01",
    type: "work",
    title: "Canary deploy spike on staging",
    details:
      "10% traffic split via the LB, promote on clean error-rate window. Rough but works; productionizing is a Q3 item.",
    effortHours: 3,
    source: "manual",
    tags: ["deploy", "canary"],
    links: [],
    nextAction: "Write up canary findings for Q2 planning",
  },
  {
    id: "act-048",
    projectId: "openops",
    date: "2026-04-08",
    type: "meeting",
    title: "Q2 ops planning",
    details:
      "Committed to: pipeline v2 migration for all services, deploy-duration dashboards, alert-noise reduction. Canary rollout deferred to Q3.",
    effortHours: 1,
    source: "manual",
    tags: ["planning", "sync"],
    links: [],
  },
  {
    id: "act-049",
    projectId: "openops",
    date: "2026-04-15",
    type: "work",
    title: "Parallelize smoke tests in deploy stage",
    details:
      "Smoke suite now fans out 8-wide; deploy stage wall time down from 11m to 4m.",
    effortHours: 2.5,
    source: "manual",
    tags: ["ci", "perf"],
    links: [],
    nextAction: "Profile the two slowest smoke tests next",
  },
  {
    id: "act-050",
    projectId: "openops",
    date: "2026-04-22",
    type: "decision",
    title: "Decision: GH Actions + self-hosted runners, no Jenkins",
    details:
      "Standardized on GitHub Actions with self-hosted LXD runners for everything. One CI grammar, and the Jenkins box gets decommissioned.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "ci"],
    links: [],
  },
  {
    id: "act-051",
    projectId: "openops",
    date: "2026-04-29",
    type: "work",
    title: "Provisioned ops-runner-03 and ops-runner-04",
    details:
      "Two more LXD VM runners from the shared image. Pool is now four; queue times at peak dropped under a minute.",
    effortHours: 2,
    source: "manual",
    tags: ["ci", "infra"],
    links: [],
  },
  {
    id: "act-052",
    projectId: "openops",
    date: "2026-05-06",
    type: "work",
    title: "Grafana: deploy duration p50/p95 dashboard",
    details:
      "Pipeline emits per-stage timings; dashboard breaks them down by service and stage.",
    effortHours: 2,
    source: "manual",
    tags: ["observability"],
    links: [
      {
        label: "Grafana: deploys",
        url: "https://grafana.internal.grewelltech.com/d/ops-deploys",
      },
    ],
    nextAction: "Add a per-stage breakdown panel",
  },
  {
    id: "act-053",
    projectId: "openops",
    date: "2026-05-08",
    type: "work",
    title: "Fix secret leak in deploy failure logs",
    details:
      "The vault-fetch error path echoed the raw token into step output. Masked at the logger, rotated the exposed token, grepped history — no other hits.",
    effortHours: 2,
    source: "manual",
    tags: ["security", "ci"],
    links: [],
  },
  {
    id: "act-054",
    projectId: "openops",
    date: "2026-05-13",
    type: "work",
    title: "Blue/green cutover automation for api tier",
    details:
      "Scripted the LB flip with health-verify and instant rollback. Manual cutovers took 20 nervous minutes; now it's one command.",
    effortHours: 4,
    source: "manual",
    tags: ["deploy"],
    links: [],
  },
  {
    id: "act-055",
    projectId: "openops",
    date: "2026-05-20",
    type: "milestone",
    title: "Pipeline v2 live for all 11 services",
    details:
      "Last two services migrated. Every deploy now goes through the same build/smoke/health-gate stages.",
    effortHours: 1.5,
    source: "manual",
    tags: ["milestone", "ci"],
    links: [],
  },
  {
    id: "act-056",
    projectId: "openops",
    date: "2026-05-27",
    type: "work",
    title: "Alert noise pass: silenced 6 flapping alerts",
    details:
      "Six alerts flapped through the weekend with zero user impact. Silenced with expiry dates and tickets to fix thresholds properly.",
    effortHours: 1.5,
    source: "capture",
    tags: ["alerting"],
    links: [],
    nextAction: "Fix thresholds before the silences expire",
  },
  {
    id: "act-057",
    projectId: "openops",
    date: "2026-06-01",
    type: "work",
    title: "Auto-collect deploy context for postmortems",
    details:
      "On failed deploys the pipeline now snapshots config diff, recent commits, and health-gate logs into the incident folder automatically.",
    effortHours: 2.5,
    source: "manual",
    tags: ["tooling", "incident"],
    links: [],
  },
  {
    id: "act-058",
    projectId: "openops",
    date: "2026-06-05",
    type: "meeting",
    title: "Incident review: billing-svc failed deploy 5/29",
    details:
      "Root cause was a stale schema migration ordering assumption. Action items: migration lint in pipeline, plus deploy-context auto-collect (already done).",
    effortHours: 1,
    source: "manual",
    tags: ["incident", "sync"],
    links: [],
  },
  {
    id: "act-059",
    projectId: "openops",
    date: "2026-06-10",
    type: "work",
    title: "Health-gate timeout flake shows up in deploy stage",
    details:
      "Deploy stage failing intermittently at the health-check gate — 3 of the last 20 runs, different services each time. Nothing obvious in service logs.",
    effortHours: 2,
    source: "capture",
    tags: ["flake", "ci"],
    links: [],
    nextAction: "Add debug logging to the health gate",
  },
  {
    id: "act-060",
    projectId: "openops",
    date: "2026-06-10",
    type: "work",
    title: "Added debug logging to health gate",
    details:
      "Gate now logs each probe attempt with latency and socket errors. Should tell us whether timeouts are service-side or network-side.",
    effortHours: 1,
    source: "manual",
    tags: ["flake", "ci"],
    links: [],
  },
  {
    id: "act-061",
    projectId: "openops",
    date: "2026-06-10",
    type: "work",
    title: "Flakes correlate 100% with ops-runner-02",
    details:
      "Pulled 30 days of runs: every health-gate timeout executed on ops-runner-02. Other three runners are clean.",
    effortHours: 1.5,
    source: "manual",
    tags: ["flake", "ci"],
    links: [],
    nextAction: "Diff runner-02 host config against runner-01",
  },
  {
    id: "act-062",
    projectId: "openops",
    date: "2026-06-16",
    type: "work",
    title: "Ruled out clock skew on runner-02",
    details:
      "chrony is healthy, offsets under 1 ms. Probe logs show connect timeouts, not slow responses — smells like packet loss on the runner itself.",
    effortHours: 2,
    source: "capture",
    tags: ["flake", "debug"],
    links: [],
  },
  {
    id: "act-063",
    projectId: "openops",
    date: "2026-06-19",
    type: "work",
    title: "Stopgap: retry on health gate",
    details:
      "One retry with a 10 s gap hides the flake for now. Explicitly marked as a stopgap in the config with a link to the investigation.",
    effortHours: 1.5,
    source: "manual",
    tags: ["flake", "stopgap"],
    links: [],
  },
  {
    id: "act-064",
    projectId: "openops",
    date: "2026-06-24",
    type: "work",
    title: "Terraform for alert rules",
    details:
      "Alert rules moved from click-ops into terraform. Reviewed and merged the module; prod applied cleanly.",
    effortHours: 2,
    source: "manual",
    tags: ["alerting", "iac"],
    links: [
      { label: "PR #87", url: "https://github.com/grewelltech/openops/pull/87" },
    ],
  },
  {
    id: "act-065",
    projectId: "openops",
    date: "2026-06-29",
    type: "work",
    title: "Deploy success SLO doc: target 99%",
    details:
      "Defined success as no rollback within 30 minutes. June lands at 97.2% — the flake is most of the gap.",
    effortHours: 1.5,
    source: "manual",
    tags: ["slo", "docs"],
    links: [],
  },
  {
    id: "act-066",
    projectId: "openops",
    date: "2026-07-07",
    type: "work",
    title: "Flake returns after runner image update",
    details:
      "Health-gate timeouts back on runner-02 after the monthly image refresh — so it survives a rebuild. Points at hardware or host config, not image state.",
    effortHours: 2,
    source: "capture",
    tags: ["flake", "ci"],
    links: [],
  },
  {
    id: "act-067",
    projectId: "openops",
    date: "2026-07-10",
    type: "blocker",
    title: "ops-runner-02 pulled from pool; no root cause",
    details:
      "Removed runner-02 from the pool to protect the SLO. Down a runner until the root cause is found — queue times up ~2 min at peak.",
    effortHours: 1,
    source: "manual",
    tags: ["blocker", "ci"],
    links: [],
    nextAction: "Get a maintenance window to poke at the host directly",
  },
  {
    id: "act-068",
    projectId: "openops",
    date: "2026-07-14",
    type: "work",
    title: "Deploy stage clean since runner-02 removal",
    details: "40 consecutive green runs across the remaining three runners. Confirms the machine, not the pipeline.",
    effortHours: 1.5,
    source: "manual",
    tags: ["flake", "ci"],
    links: [],
  },
  {
    id: "act-069",
    projectId: "openops",
    date: "2026-07-15",
    type: "work",
    title: "Alert routing: page only on user-facing SLOs",
    details:
      "Applied the March severity-tier agreement for real: 9 alerts demoted from page to ticket. On-call load should drop noticeably.",
    effortHours: 2,
    source: "manual",
    tags: ["alerting"],
    links: [],
  },
  {
    id: "act-070",
    projectId: "openops",
    date: "2026-07-16",
    type: "meeting",
    title: "Ops sync: runner-02 saga retro",
    details:
      "Agreed to keep runner-02 out of the pool until root-caused, and to add per-runner failure-rate alerting so the next one is caught in days, not weeks.",
    effortHours: 1,
    source: "manual",
    tags: ["sync", "ci"],
    links: [],
  },
  {
    id: "act-071",
    projectId: "openops",
    date: "2026-07-20",
    type: "work",
    title: "Root cause: nf_conntrack exhaustion on runner-02",
    details:
      "dmesg on the host: 'nf_conntrack: table full, dropping packet' exactly during parallel smoke tests. Runner-02 had the distro-default nf_conntrack_max while the others got the tuned sysctl — dropped packets looked like health-gate timeouts.",
    effortHours: 3,
    source: "manual",
    tags: ["rootcause", "ci"],
    links: [
      {
        label: "Grafana: runner conntrack",
        url: "https://grafana.internal.grewelltech.com/d/runner-conntrack",
      },
    ],
    nextAction: "Raise the sysctl via config mgmt and return runner-02 to the pool",
  },
  {
    id: "act-072",
    projectId: "openops",
    date: "2026-07-21",
    type: "work",
    title: "Raised nf_conntrack_max; runner-02 back in pool",
    details:
      "Sysctl now enforced by config management for all runners, so drift can't recreate this. Runner-02 back in the pool; watching failure-rate alert.",
    effortHours: 1,
    source: "manual",
    tags: ["fix", "ci"],
    links: [],
  },
  {
    id: "act-073",
    projectId: "openops",
    date: "2026-07-23",
    type: "work",
    title: "Deploy annotations via Grafana API",
    details:
      "Pipeline now posts an annotation per deploy — service, version, duration. Incident timelines line up against dashboards for free.",
    effortHours: 2,
    source: "manual",
    tags: ["observability"],
    links: [],
  },
  {
    id: "act-074",
    projectId: "openops",
    date: "2026-07-23",
    type: "decision",
    title: "Decision: deploy freeze Fridays after 15:00",
    details:
      "Two Friday-evening rollbacks in June were enough. Exceptions need on-call approval; enforcement is a pipeline check, not a policy doc.",
    effortHours: 0.5,
    source: "manual",
    tags: ["decision", "deploy"],
    links: [],
  },
  {
    id: "act-075",
    projectId: "openops",
    date: "2026-07-24",
    type: "work",
    title: "Weekly deploy report automation started",
    details:
      "Script pulls deploy counts, success rate, and duration percentiles into a Friday summary. Half done — formatting and delivery left.",
    effortHours: 1.5,
    source: "manual",
    tags: ["tooling", "reporting"],
    links: [],
    nextAction: "Finish report formatting and wire up delivery",
  },

  // ── Home Infrastructure ─────────────────────────────────────────────────
  {
    id: "act-076",
    projectId: "home-infra",
    date: "2026-03-07",
    type: "work",
    title: "Puppet module cleanup: roles/profiles split",
    details:
      "Untangled node manifests into proper roles and profiles. Every host now gets exactly one role class.",
    effortHours: 3,
    source: "manual",
    tags: ["puppet"],
    links: [],
  },
  {
    id: "act-077",
    projectId: "home-infra",
    date: "2026-03-14",
    type: "work",
    title: "MAAS 3.5 upgrade on maas-ctrl",
    details:
      "Snap refresh plus postgres backup first. Recommissioned one spare node afterward to verify PXE and image sync still work.",
    effortHours: 2.5,
    source: "manual",
    tags: ["maas", "upgrade"],
    links: [],
    nextAction: "Recommission the remaining nodes over the next couple weekends",
  },
  {
    id: "act-078",
    projectId: "home-infra",
    date: "2026-03-21",
    type: "work",
    title: "VLAN 30 (lab) trunked to office drop",
    details:
      "sw-core port 12 now trunks VLANs 10/20/30 to the office. Lab gear reachable from the desk without hairpinning through the firewall.",
    effortHours: 2,
    source: "manual",
    tags: ["network", "vlan"],
    links: [
      {
        label: "VLAN plan",
        url: "https://wiki.internal.grewelltech.com/homelab/vlan-plan",
      },
    ],
  },
  {
    id: "act-079",
    projectId: "home-infra",
    date: "2026-03-28",
    type: "work",
    title: "restic snapshot verify and prune",
    details:
      "restic check --read-data-subset=10% on both repos, then prune to policy. Offsite repo healthy; local repo reclaimed 40 GB.",
    effortHours: 2,
    source: "manual",
    tags: ["backup"],
    links: [],
  },
  {
    id: "act-080",
    projectId: "home-infra",
    date: "2026-04-04",
    type: "work",
    title: "LXD 5.21 cluster plan for three nodes",
    details:
      "Sketched cluster on lxd-01..03 with ZFS pools per node, cluster over VLAN 10. Migration order: stateless containers first, DNS/DHCP last.",
    effortHours: 2,
    source: "manual",
    tags: ["lxd", "planning"],
    links: [],
    nextAction: "Bootstrap lxd-01 next Saturday",
  },
  {
    id: "act-081",
    projectId: "home-infra",
    date: "2026-04-11",
    type: "work",
    title: "lxd-01 bootstrapped, lxd-02 joined",
    details:
      "Cluster init on lxd-01, join token for lxd-02, ZFS pools online on both. Test container live-migrated between them cleanly.",
    effortHours: 4,
    source: "manual",
    tags: ["lxd"],
    links: [],
    nextAction: "Join lxd-03 next Saturday",
  },
  {
    id: "act-082",
    projectId: "home-infra",
    date: "2026-04-18",
    type: "work",
    title: "lxd-03 joined; ZFS layout finalized",
    details:
      "Third node in; three-node quorum happy. Settled on mirrored pairs per node rather than raidz — resilver time beats capacity here.",
    effortHours: 3,
    source: "manual",
    tags: ["lxd", "zfs"],
    links: [],
  },
  {
    id: "act-083",
    projectId: "home-infra",
    date: "2026-04-25",
    type: "milestone",
    title: "All VLANs segmented; IoT isolated",
    details:
      "Final firewall rules in: IoT (VLAN 40) can reach the internet and nothing else, guest is fully isolated, lab reaches mgmt one-way.",
    effortHours: 2.5,
    source: "manual",
    tags: ["network", "milestone"],
    links: [],
  },
  {
    id: "act-084",
    projectId: "home-infra",
    date: "2026-05-02",
    type: "work",
    title: "First six containers migrated to LXD cluster",
    details:
      "Stateless services first: unifi, grafana, uptime-kuma and friends. All moved with lxc move, zero drama.",
    effortHours: 3,
    source: "manual",
    tags: ["lxd", "migration"],
    links: [],
    nextAction: "Plan the DNS/DHCP staged cutover before moving them",
  },
  {
    id: "act-085",
    projectId: "home-infra",
    date: "2026-05-09",
    type: "work",
    title: "Puppet ENC script for node classification",
    details:
      "Small external node classifier reading a YAML inventory. Role assignment out of site.pp; adding a host is now one YAML line.",
    effortHours: 2.5,
    source: "manual",
    tags: ["puppet"],
    links: [],
  },
  {
    id: "act-086",
    projectId: "home-infra",
    date: "2026-05-16",
    type: "work",
    title: "NUT + UPS runtime test on pve-01",
    details:
      "Pulled the plug for real: 14 minutes runtime at current load, clean shutdown fired at 20%. NUT client on lxd nodes still TODO.",
    effortHours: 2,
    source: "manual",
    tags: ["power", "ups"],
    links: [],
    nextAction: "Add NUT clients on lxd-01..03",
  },
  {
    id: "act-087",
    projectId: "home-infra",
    date: "2026-05-19",
    type: "work",
    title: "Quick evening fix: DHCP relay for VLAN 40",
    details:
      "IoT devices lost leases after the firewall update — relay wasn't forwarding to the new DHCP container address. One-line fix.",
    effortHours: 1,
    source: "capture",
    tags: ["network", "dhcp"],
    links: [],
  },
  {
    id: "act-088",
    projectId: "home-infra",
    date: "2026-05-30",
    type: "work",
    title: "Remaining containers migrated off pve-01",
    details:
      "DNS and DHCP moved last with a staged cutover — secondary up on the cluster before demoting the old primary. No lease gaps observed.",
    effortHours: 3.5,
    source: "manual",
    tags: ["lxd", "migration"],
    links: [],
  },
  {
    id: "act-089",
    projectId: "home-infra",
    date: "2026-06-06",
    type: "work",
    title: "restic repo check plus offsite sync",
    details: "Monthly check clean on both repos; offsite sync caught up after the May migration churn.",
    effortHours: 1.5,
    source: "manual",
    tags: ["backup"],
    links: [],
  },
  {
    id: "act-090",
    projectId: "home-infra",
    date: "2026-06-13",
    type: "milestone",
    title: "LXD cluster migration complete; pve-01 is VM-only",
    details:
      "Every container now lives on the cluster. pve-01 keeps only the three VMs that genuinely need a hypervisor.",
    effortHours: 2,
    source: "manual",
    tags: ["lxd", "milestone"],
    links: [],
  },
  {
    id: "act-091",
    projectId: "home-infra",
    date: "2026-06-17",
    type: "blocker",
    title: "MAAS IPMI power queries timing out",
    details:
      "maas-ctrl logs 'Failed to query power state' for two nodes; ipmitool from the same box works fine. Can't power-cycle from MAAS until resolved — possibly fixed in 3.6.",
    effortHours: 1.5,
    source: "capture",
    tags: ["maas", "ipmi"],
    links: [],
    nextAction: "Check MAAS 3.6 release notes for IPMI fixes",
  },
  {
    id: "act-092",
    projectId: "home-infra",
    date: "2026-06-20",
    type: "work",
    title: "node_exporter + Grafana on all lab hosts",
    details:
      "Puppet profile rolls node_exporter everywhere; single lab-overview dashboard with disk, temp, and conntrack panels.",
    effortHours: 2.5,
    source: "manual",
    tags: ["observability"],
    links: [
      {
        label: "Grafana: lab overview",
        url: "https://grafana.lab.grewelltech.com/d/lab-overview",
      },
    ],
  },
  {
    id: "act-093",
    projectId: "home-infra",
    date: "2026-06-27",
    type: "decision",
    title: "Decision: keeping Puppet, no Ansible migration",
    details:
      "Considered migrating for the third time. The inventory is deeply Puppet-shaped (roles/profiles, ENC, eyaml) and it works. Revisit only if the agent EOLs.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "puppet"],
    links: [],
  },
  {
    id: "act-094",
    projectId: "home-infra",
    date: "2026-07-04",
    type: "blocker",
    title: "pve-01 PSU failed during monthly reboot",
    details:
      "No POST after the scheduled reboot; PSU fan dead and burnt smell. Cold-migrated the three VMs to lxd-01 as emergency VMs. Box stays down until a PSU swap.",
    effortHours: 3,
    source: "manual",
    tags: ["hardware", "blocker"],
    links: [],
    nextAction: "Source a replacement PSU; check the retired chassis for a compatible spare",
  },
  {
    id: "act-095",
    projectId: "home-infra",
    date: "2026-07-11",
    type: "work",
    title: "Temp PSU swap from retired chassis; pve-01 back up",
    details:
      "The old Supermicro spare fits and holds under load. VMs migrated back. Proper replacement still on order — the spare is a stopgap.",
    effortHours: 2,
    source: "manual",
    tags: ["hardware"],
    links: [],
  },
  {
    id: "act-096",
    projectId: "home-infra",
    date: "2026-07-11",
    type: "work",
    title: "Puppet agents 401 on three hosts — parked",
    details:
      "Noticed during the weekend run: agent runs failing with 401s pulling the control repo. Out of weekend budget after the PSU work; parked for next week.",
    effortHours: 1,
    source: "capture",
    tags: ["puppet", "auth"],
    links: [],
    nextAction: "Dig into the 401s — smells like a credential expiry",
  },
  {
    id: "act-097",
    projectId: "home-infra",
    date: "2026-07-12",
    type: "work",
    title: "MAAS image sync plus commissioning test",
    details:
      "Synced new Ubuntu 26.04 images and commissioned the spare node end-to-end. IPMI timeout from 6/17 still present for the same two nodes.",
    effortHours: 1.5,
    source: "manual",
    tags: ["maas"],
    links: [],
  },
  {
    id: "act-098",
    projectId: "home-infra",
    date: "2026-07-18",
    type: "work",
    title: "Weekly backup verify and snapshot rotation check",
    details: "Spot-restored two files from last week's snapshots. LXD snapshot rotation running on schedule.",
    effortHours: 1,
    source: "manual",
    tags: ["backup"],
    links: [],
  },
  {
    id: "act-099",
    projectId: "home-infra",
    date: "2026-07-19",
    type: "work",
    title: "Fixed Puppet PAT expiry breaking agent runs",
    details:
      "The 401s were the GitHub PAT for r10k expiring silently — agents couldn't fetch the control repo. Took ~2h to trace because the agent error pointed at the puppetserver, not the git fetch. Rotated the token, moved it into hiera-eyaml, and set a reminder ahead of the next 90-day expiry.",
    effortHours: 2,
    source: "manual",
    tags: ["puppet", "auth"],
    links: [],
    nextAction: "Rotate the remaining service PATs before they bite the same way",
  },
  {
    id: "act-100",
    projectId: "home-infra",
    date: "2026-07-25",
    type: "work",
    title: "Replacement PSU arrived; bench-tested",
    details:
      "New unit tested on the bench with a dummy load — rails clean. Install into pve-01 planned for next Saturday to keep today light.",
    effortHours: 1,
    source: "capture",
    tags: ["hardware"],
    links: [],
  },

  // ── 5G Testbed ──────────────────────────────────────────────────────────
  {
    id: "act-101",
    projectId: "5g-testbed",
    date: "2026-03-17",
    type: "research",
    title: "Survey: srsRAN vs OAI for the lab gNB",
    details:
      "Read both projects' docs and recent issue traffic. srsRAN's ZMQ sim mode means core bring-up can start before any RF exists.",
    effortHours: 2,
    source: "manual",
    tags: ["srsran", "reading"],
    links: [],
  },
  {
    id: "act-102",
    projectId: "5g-testbed",
    date: "2026-03-26",
    type: "decision",
    title: "Decision: srsRAN Project over OAI",
    details:
      "Better docs, healthier community, and ZMQ sim mode for RF-free bring-up. OAI stays on the list if I ever need features srsRAN gates.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "srsran"],
    links: [],
  },
  {
    id: "act-103",
    projectId: "5g-testbed",
    date: "2026-04-02",
    type: "work",
    title: "Open5GS core up on core-5g VM",
    details:
      "v2.7 installed on the core-5g VM, AMF/SMF/UPF configured for PLMN 999/70, first subscriber added via WebUI.",
    effortHours: 3,
    source: "manual",
    tags: ["open5gs", "core"],
    links: [{ label: "Open5GS docs", url: "https://open5gs.org/open5gs/docs/" }],
    nextAction: "Bring up the srsRAN gNB in ZMQ sim against this core",
  },
  {
    id: "act-104",
    projectId: "5g-testbed",
    date: "2026-04-06",
    type: "work",
    title: "srsRAN gNB + ZMQ UE attach in sim",
    details:
      "gNB and srsUE over ZMQ against the Open5GS core: full registration and PDU session, no RF involved. Core config is proven before hardware.",
    effortHours: 3,
    source: "manual",
    tags: ["srsran", "sim"],
    links: [{ label: "srsRAN docs", url: "https://docs.srsran.com/projects/project/" }],
    nextAction: "Rack the RAN550 and start hardware bring-up",
  },
  {
    id: "act-105",
    projectId: "5g-testbed",
    date: "2026-04-10",
    type: "work",
    title: "RAN550 unboxed and racked in the lab",
    details:
      "2U unit racked as ran550-lab, power fed, TX ports capped until the attenuator chain is in place. Wiring captured in the rack note.",
    effortHours: 2,
    source: "manual",
    tags: ["ran550", "hardware"],
    links: [],
  },
  {
    id: "act-106",
    projectId: "5g-testbed",
    date: "2026-04-14",
    type: "work",
    title: "RAN550 mgmt interface up on VLAN 30",
    details: "Static addressing on the lab VLAN, mgmt UI and SSH reachable from the desk.",
    effortHours: 2,
    source: "manual",
    tags: ["ran550", "network"],
    links: [],
  },
  {
    id: "act-107",
    projectId: "5g-testbed",
    date: "2026-04-14",
    type: "work",
    title: "First boot: fw 6.1.2, license gates cell config",
    details:
      "Unit boots clean on firmware 6.1.2 but cell activation is behind licensed features. Single-cell eval works; anything more needs a lab license SKU.",
    effortHours: 1.5,
    source: "manual",
    tags: ["ran550", "licensing"],
    links: [],
    nextAction: "Get a licensing contact from the vendor",
  },
  {
    id: "act-108",
    projectId: "5g-testbed",
    date: "2026-04-17",
    type: "meeting",
    title: "Intro call with Dan (vendor AE) re: lab licensing",
    details:
      "Walked through the lab use case. Need: 2-cell lab license for n78 plus firmware support. Dan to come back with SKU options.",
    effortHours: 1,
    source: "manual",
    tags: ["vendor", "licensing"],
    links: [],
  },
  {
    id: "act-109",
    projectId: "5g-testbed",
    date: "2026-04-22",
    type: "work",
    title: "Attenuator chain bench: 30+30 dB fixed pads",
    details:
      "Built the fixed chain: two 30 dB pads rated for the TX power, N-type throughout. Programmable attenuator still to be ordered for mobility tests.",
    effortHours: 2,
    source: "manual",
    tags: ["rf", "bench"],
    links: [],
  },
  {
    id: "act-110",
    projectId: "5g-testbed",
    date: "2026-04-22",
    type: "work",
    title: "RAN550 TX cabled through pads to UE bench",
    details: "Conducted setup end to end — no radiated emissions. Cable losses measured and logged in the wiring note.",
    effortHours: 1.5,
    source: "manual",
    tags: ["rf", "bench"],
    links: [],
  },
  {
    id: "act-111",
    projectId: "5g-testbed",
    date: "2026-04-22",
    type: "work",
    title: "Spectrum sanity check of the n78 carrier",
    details:
      "tinySA on the far side of the pad chain: carrier centered where configured at 3.5 GHz, level as expected into the dummy load.",
    effortHours: 1.5,
    source: "manual",
    tags: ["rf", "spectrum"],
    links: [],
    nextAction: "Attempt first UE attach over the pad chain",
  },
  {
    id: "act-112",
    projectId: "5g-testbed",
    date: "2026-05-01",
    type: "work",
    title: "UE attach attempt: PLMN mismatch, fixed",
    details:
      "Quectel RM520N refused to register — SIM PLMN didn't match the core's 999/70. Aligned AMF config and SIM programming; registration proceeds to auth.",
    effortHours: 2.5,
    source: "manual",
    tags: ["ue", "debug"],
    links: [],
  },
  {
    id: "act-113",
    projectId: "5g-testbed",
    date: "2026-05-07",
    type: "work",
    title: "Programmed sysmoISIM test SIMs for lab PLMN",
    details:
      "Four SIMs programmed with pySim for 999/70, keys loaded into Open5GS subscriber DB. Attach gets through auth now.",
    effortHours: 2,
    source: "manual",
    tags: ["sim", "ue"],
    links: [],
    nextAction: "Full end-to-end attach attempt with the new SIMs",
  },
  {
    id: "act-114",
    projectId: "5g-testbed",
    date: "2026-05-15",
    type: "milestone",
    title: "First end-to-end attach through RAN550",
    details:
      "UE registered, PDU session up, traffic flowing: ~89 Mbps down through 60 dB of pads. The whole chain — UE, RAN550, Open5GS — works on real hardware.",
    effortHours: 3,
    source: "manual",
    tags: ["milestone", "ran550"],
    links: [],
  },
  {
    id: "act-115",
    projectId: "5g-testbed",
    date: "2026-05-22",
    type: "work",
    title: "Throughput tuning: MTU and UPF buffers",
    details:
      "GTP-U encapsulation was fragmenting at default MTU; fixed MTU on the N3 path and bumped UPF buffer sizes. 89 → 112 Mbps down.",
    effortHours: 2.5,
    source: "manual",
    tags: ["perf", "upf"],
    links: [],
    nextAction: "Commit the MTU fix to the config repo with a do-not-revert note",
  },
  {
    id: "act-116",
    projectId: "5g-testbed",
    date: "2026-05-26",
    type: "blocker",
    title: "Programmable attenuator back-ordered",
    details:
      "ETA slipped to July. Mobility/fade testing parked; fixed pads limit us to static-link scenarios meanwhile.",
    effortHours: 0.5,
    source: "capture",
    tags: ["blocker", "rf"],
    links: [],
  },
  {
    id: "act-117",
    projectId: "5g-testbed",
    date: "2026-06-02",
    type: "work",
    title: "Open5GS 2.7.2 upgrade; configs into git",
    details:
      "Upgraded core-5g and moved all of /etc/open5gs under git with a deploy script. Config drift was becoming untrackable.",
    effortHours: 2,
    source: "manual",
    tags: ["open5gs", "config"],
    links: [],
  },
  {
    id: "act-118",
    projectId: "5g-testbed",
    date: "2026-06-08",
    type: "work",
    title: "Two-cell handover rig design (license-gated)",
    details:
      "Designed the two-cell layout with the programmable attenuator crossfading between cells. Second cell can't activate without the license, but the design is ready.",
    effortHours: 2,
    source: "manual",
    tags: ["design", "handover"],
    links: [],
  },
  {
    id: "act-119",
    projectId: "5g-testbed",
    date: "2026-06-12",
    type: "meeting",
    title: "Call with Dan: licensing quote formally requested",
    details:
      "Asked for a formal quote — 2-cell lab license plus firmware support, n78. Dan owes the quote; said days, not weeks.",
    effortHours: 0.5,
    source: "manual",
    tags: ["vendor", "licensing"],
    links: [],
    nextAction: "Chase if nothing lands within two weeks",
  },
  {
    id: "act-120",
    projectId: "5g-testbed",
    date: "2026-06-18",
    type: "work",
    title: "Automated attach smoke test (pytest + AT commands)",
    details:
      "pytest drives the RM520N over AT commands: attach, PDU session check, ping through the UPF, detach. Runs in under a minute; catches config regressions.",
    effortHours: 3,
    source: "manual",
    tags: ["testing", "automation"],
    links: [],
  },
  {
    id: "act-121",
    projectId: "5g-testbed",
    date: "2026-06-26",
    type: "work",
    title: "Chased Dan on the quote — 'next week'",
    details: "Two weeks since the ask. Polite nudge sent; answer was next week. Noting it here so the timeline shows the gap isn't mine.",
    effortHours: 0.5,
    source: "capture",
    tags: ["vendor", "licensing"],
    links: [],
  },
  {
    id: "act-122",
    projectId: "5g-testbed",
    date: "2026-07-06",
    type: "blocker",
    title: "RAN550 licensing quote still pending from Dan",
    details:
      "Three weeks since the formal request, one chase ignored. Second cell and all handover work fully blocked on this. Flipping the project to waiting.",
    effortHours: 0.5,
    source: "manual",
    tags: ["blocker", "vendor"],
    links: [],
    nextAction: "Email Dan a nudge with a decision deadline",
  },

  // ── Personal Website ────────────────────────────────────────────────────
  {
    id: "act-123",
    projectId: "personal-website",
    date: "2026-03-08",
    type: "work",
    title: "Site audit: Hugo 0.92, theme abandoned",
    details:
      "Current site is Hugo 0.92 with a theme last touched in 2022. Content is four posts and a stale about page.",
    effortHours: 1.5,
    source: "manual",
    tags: ["audit"],
    links: [],
  },
  {
    id: "act-124",
    projectId: "personal-website",
    date: "2026-03-15",
    type: "research",
    title: "Eval: stay on Hugo vs Astro vs plain HTML",
    details:
      "Astro's content collections fit the posts-plus-projects shape best. Plain HTML tempting but I'd regret it at post #5.",
    effortHours: 1.5,
    source: "manual",
    tags: ["eval"],
    links: [],
  },
  {
    id: "act-125",
    projectId: "personal-website",
    date: "2026-03-29",
    type: "work",
    title: "New site outline drafted",
    details: "Three sections: projects, notes, about. Homelab writeup planned as the relaunch anchor post.",
    effortHours: 1,
    source: "manual",
    tags: ["writing"],
    links: [],
  },
  {
    id: "act-126",
    projectId: "personal-website",
    date: "2026-04-05",
    type: "work",
    title: "Astro starter spiked with content collections",
    details: "Repo at ~/repos/site-next. Collections wired for posts and projects; markdown renders with the stock theme.",
    effortHours: 2,
    source: "manual",
    tags: ["astro"],
    links: [],
  },
  {
    id: "act-127",
    projectId: "personal-website",
    date: "2026-04-12",
    type: "work",
    title: "Ported four old posts, fixed frontmatter",
    details: "Hugo frontmatter converted, image paths fixed, one dead link removed.",
    effortHours: 1.5,
    source: "manual",
    tags: ["migration"],
    links: [],
  },
  {
    id: "act-128",
    projectId: "personal-website",
    date: "2026-04-26",
    type: "work",
    title: "Homepage layout and typography pass",
    details: "Simple single-column layout, system font stack. Good enough — resisting the urge to redesign forever.",
    effortHours: 2,
    source: "manual",
    tags: ["design"],
    links: [],
  },
  {
    id: "act-129",
    projectId: "personal-website",
    date: "2026-05-03",
    type: "work",
    title: "Cloudflare Pages preview deploy set up",
    details: "Pushes to main build and deploy to a preview URL automatically. DNS cutover deliberately left for launch.",
    effortHours: 1.5,
    source: "manual",
    tags: ["deploy"],
    links: [
      { label: "Pages preview", url: "https://site-next.pages.dev" },
    ],
  },
  {
    id: "act-130",
    projectId: "personal-website",
    date: "2026-05-08",
    type: "work",
    title: "Homelab writeup half-drafted, stalled",
    details:
      "Got through the MAAS and Puppet sections, stalled at the LXD migration part. Draft sits mid-section 3 in content/posts/homelab.md.",
    effortHours: 1,
    source: "capture",
    tags: ["writing"],
    links: [],
    nextAction: "Finish section 3 — the outline for the rest is already in the file",
  },

  // ── AI Assistant Research ───────────────────────────────────────────────
  {
    id: "act-131",
    projectId: "ai-research",
    date: "2026-03-05",
    type: "research",
    title: "MCP spec read-through",
    details:
      "Read the spec and skimmed the reference servers. Resources vs tools distinction matters more than I expected for a notes server.",
    effortHours: 1.5,
    source: "manual",
    tags: ["mcp", "reading"],
    links: [
      { label: "MCP spec", url: "https://modelcontextprotocol.io/specification" },
    ],
  },
  {
    id: "act-132",
    projectId: "ai-research",
    date: "2026-03-13",
    type: "research",
    title: "Local embedding models: bge-m3 vs nomic-embed",
    details:
      "Compared on 200 of my own notes. bge-m3 noticeably better on technical shorthand; speed difference irrelevant at my scale.",
    effortHours: 2,
    source: "manual",
    tags: ["embeddings", "eval"],
    links: [],
    nextAction: "Standardize the spike on bge-m3",
  },
  {
    id: "act-133",
    projectId: "ai-research",
    date: "2026-03-20",
    type: "work",
    title: "sqlite-vec spike with 5k markdown notes",
    details:
      "Indexed the whole notes folder into a single sqlite file. Query latency ~30 ms; zero infrastructure. This is the right shape for personal tooling.",
    effortHours: 2,
    source: "manual",
    tags: ["rag", "sqlite"],
    links: [
      { label: "sqlite-vec", url: "https://github.com/asg017/sqlite-vec" },
    ],
  },
  {
    id: "act-134",
    projectId: "ai-research",
    date: "2026-04-03",
    type: "research",
    title: "Chunking strategies: heading-aware wins",
    details:
      "Tested fixed-size vs heading-aware chunking on my notes. Heading-aware chunks keep answers self-contained; fixed-size splits config blocks mid-snippet.",
    effortHours: 1.5,
    source: "manual",
    tags: ["rag", "chunking"],
    links: [],
  },
  {
    id: "act-135",
    projectId: "ai-research",
    date: "2026-04-13",
    type: "decision",
    title: "Decision: sqlite-vec over Qdrant for notes RAG",
    details:
      "Single file, no daemon, and recall parity with Qdrant at my corpus size (≤50k chunks). Qdrant is the answer to a scale problem I don't have.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "rag"],
    links: [],
  },
  {
    id: "act-136",
    projectId: "ai-research",
    date: "2026-04-24",
    type: "work",
    title: "Minimal MCP server exposing note search",
    details:
      "Go server with one search tool over the sqlite-vec index. Streams top-k chunks with source paths.",
    effortHours: 3,
    source: "manual",
    tags: ["mcp", "go"],
    links: [],
    nextAction: "Dogfood it from the editor for a week",
  },
  {
    id: "act-137",
    projectId: "ai-research",
    date: "2026-05-11",
    type: "research",
    title: "Agent eval reading: pass^k, rubric grading",
    details:
      "Read up on eval methodology for agents. Takeaway: small curated QA sets over my own data beat generic benchmarks for what I care about.",
    effortHours: 1.5,
    source: "manual",
    tags: ["eval", "reading"],
    links: [],
  },
  {
    id: "act-138",
    projectId: "ai-research",
    date: "2026-05-18",
    type: "work",
    title: "Note-search MCP wired into the editor agent",
    details:
      "Week of dogfooding starts now. First impression: retrieval quality is fine, the tool description needed two rewrites before the agent used it well.",
    effortHours: 2,
    source: "manual",
    tags: ["mcp", "dogfood"],
    links: [],
  },
  {
    id: "act-139",
    projectId: "ai-research",
    date: "2026-05-29",
    type: "research",
    title: "Reranking: when a cross-encoder is worth it",
    details:
      "Tested bge-reranker on top of vector search. Helps at k>20 retrieval depth; at my typical k=8 it's a wash. Skipping for now.",
    effortHours: 1.5,
    source: "manual",
    tags: ["rag", "eval"],
    links: [],
  },
  {
    id: "act-140",
    projectId: "ai-research",
    date: "2026-06-15",
    type: "work",
    title: "Eval harness v0: 40 QA pairs over my notes",
    details:
      "Hand-wrote 40 questions with known answers from my own notes — mix of lookup, config-recall, and multi-hop. Harness scores exact-fact presence.",
    effortHours: 2.5,
    source: "manual",
    tags: ["eval", "rag"],
    links: [],
  },
  {
    id: "act-141",
    projectId: "ai-research",
    date: "2026-06-22",
    type: "milestone",
    title: "Local RAG passes 34/40 eval questions",
    details:
      "Baseline established. All six failures are multi-hop questions needing two notes joined — single-hop retrieval is basically solved.",
    effortHours: 1.5,
    source: "manual",
    tags: ["milestone", "eval"],
    links: [],
    nextAction: "Write up results; decide whether multi-hop is worth chasing",
  },
  {
    id: "act-142",
    projectId: "ai-research",
    date: "2026-07-03",
    type: "research",
    title: "Structured outputs for extraction tasks",
    details:
      "Read up on schema-constrained generation. Directly relevant to turning raw work logs into typed timeline entries.",
    effortHours: 1,
    source: "capture",
    tags: ["reading", "extraction"],
    links: [],
  },
  {
    id: "act-143",
    projectId: "ai-research",
    date: "2026-07-10",
    type: "work",
    title: "Extraction spike: raw log text to JSON timeline",
    details:
      "Prototype turns a week of my scratch log into typed entries — date, project guess, effort estimate. 80% usable; project attribution is the weak spot.",
    effortHours: 2,
    source: "manual",
    tags: ["extraction", "prototype"],
    links: [],
    nextAction: "Try a project-alias table to fix attribution",
  },
  {
    id: "act-144",
    projectId: "ai-research",
    date: "2026-07-17",
    type: "research",
    title: "MCP auth patterns for local servers",
    details:
      "Surveyed how local MCP servers handle secrets and scoping. For single-user local tools, filesystem permissions plus a bearer token is plenty.",
    effortHours: 1,
    source: "manual",
    tags: ["mcp", "security"],
    links: [],
  },
  {
    id: "act-145",
    projectId: "ai-research",
    date: "2026-07-22",
    type: "work",
    title: "RAG spike refactored into a clean Go+sqlite repo",
    details:
      "Moved from ~/spikes/rag to ~/repos/notes-rag with real structure: indexer, query CLI, MCP server as separate packages. Tests for the chunker.",
    effortHours: 2.5,
    source: "manual",
    tags: ["go", "rag"],
    links: [],
  },
  {
    id: "act-146",
    projectId: "ai-research",
    date: "2026-07-24",
    type: "research",
    title: "Notes on agent memory: episodic vs semantic",
    details:
      "Reading on memory architectures. Donezo-relevant: activity logs are episodic memory, project resumeContext is the semantic distillate.",
    effortHours: 1,
    source: "capture",
    tags: ["reading", "memory"],
    links: [],
  },

  // ── ISO Kit ─────────────────────────────────────────────────────────────
  {
    id: "act-147",
    projectId: "iso-kit",
    date: "2026-03-02",
    type: "work",
    title: "Scaffolded iso-kit CLI with stencil",
    details:
      "Command tree: build, validate, inspect. Flags typed via stencil; --help output already decent for free.",
    effortHours: 2,
    source: "manual",
    tags: ["go", "cli"],
    links: [],
  },
  {
    id: "act-148",
    projectId: "iso-kit",
    date: "2026-03-09",
    type: "work",
    title: "Primary volume descriptor writer",
    details:
      "PVD serialization with both-endian fields done properly. Verified byte-for-byte against a xorriso-produced reference image.",
    effortHours: 3,
    source: "manual",
    tags: ["iso9660"],
    links: [],
    nextAction: "Directory records and path tables next",
  },
  {
    id: "act-149",
    projectId: "iso-kit",
    date: "2026-03-12",
    type: "work",
    title: "Rock Ridge: long names and symlinks",
    details:
      "NM and SL entries implemented, including continuation areas for long names. Linux mounts show correct names and working symlinks.",
    effortHours: 3.5,
    source: "manual",
    tags: ["rockridge"],
    links: [],
  },
  {
    id: "act-150",
    projectId: "iso-kit",
    date: "2026-03-16",
    type: "work",
    title: "El Torito boot catalog support",
    details:
      "No-emulation boot entries for BIOS and UEFI. Test image boots in QEMU both ways.",
    effortHours: 3,
    source: "manual",
    tags: ["eltorito", "boot"],
    links: [],
  },
  {
    id: "act-151",
    projectId: "iso-kit",
    date: "2026-03-18",
    type: "decision",
    title: "Decision: pure Go, no shelling out to xorriso",
    details:
      "Reproducible builds and painless cross-compile beat development speed here. Accepted cost: hybrid MBR/GPT support gets built by hand.",
    effortHours: 1,
    source: "manual",
    tags: ["decision", "go"],
    links: [],
  },
  {
    id: "act-152",
    projectId: "iso-kit",
    date: "2026-03-23",
    type: "work",
    title: "Validate mode: walk plus checksum against manifest",
    details:
      "iso-kit validate walks the image, checks structure invariants, and compares file checksums against a manifest. Exit codes suit CI use.",
    effortHours: 2.5,
    source: "manual",
    tags: ["validation"],
    links: [],
  },
  {
    id: "act-153",
    projectId: "iso-kit",
    date: "2026-03-30",
    type: "work",
    title: "Joliet support behind --joliet flag",
    details: "UCS-2 supplementary descriptors for Windows compatibility. Off by default; Rock Ridge remains primary.",
    effortHours: 2,
    source: "manual",
    tags: ["joliet"],
    links: [],
  },
  {
    id: "act-154",
    projectId: "iso-kit",
    date: "2026-04-01",
    type: "work",
    title: "Fuzzed directory record parser; three crashes fixed",
    details:
      "go test -fuzz found two slice-bounds panics and an infinite loop on a crafted continuation chain. All fixed with regression seeds kept.",
    effortHours: 2.5,
    source: "manual",
    tags: ["fuzzing", "go"],
    links: [
      { label: "PR #23", url: "https://github.com/grewelltech/iso-kit/pull/23" },
    ],
  },
  {
    id: "act-155",
    projectId: "iso-kit",
    date: "2026-04-06",
    type: "work",
    title: "Hybrid MBR/GPT for USB-bootable images",
    details:
      "Protective MBR plus GPT so the same image boots from optical and USB. The hand-rolled cost of the pure-Go decision, paid off in one sitting.",
    effortHours: 4,
    source: "manual",
    tags: ["boot", "gpt"],
    links: [],
  },
  {
    id: "act-156",
    projectId: "iso-kit",
    date: "2026-04-08",
    type: "work",
    title: "Table-driven tests for path table edge cases",
    details:
      "Deep nesting, max-length names, empty dirs, case collisions. Found one sorting bug against the spec ordering rules.",
    effortHours: 2,
    source: "manual",
    tags: ["tests"],
    links: [],
  },
  {
    id: "act-157",
    projectId: "iso-kit",
    date: "2026-04-13",
    type: "work",
    title: "README quickstart plus examples",
    details: "Build-and-validate walkthrough plus a MAAS ephemeral image example — the actual use case that started this.",
    effortHours: 1.5,
    source: "manual",
    tags: ["docs"],
    links: [],
  },
  {
    id: "act-158",
    projectId: "iso-kit",
    date: "2026-04-15",
    type: "work",
    title: "v1.0.0-rc: CI matrix green on all platforms",
    details: "linux/darwin/windows, amd64+arm64. Windows path handling needed one fix; everything else was already clean.",
    effortHours: 1.5,
    source: "manual",
    tags: ["ci", "release"],
    links: [],
    nextAction: "Tag 1.0 on Friday if nothing shakes out",
  },
  {
    id: "act-159",
    projectId: "iso-kit",
    date: "2026-04-17",
    type: "milestone",
    title: "ISO Kit 1.0 shipped",
    details:
      "v1.0.0 tagged with binaries for all platforms. Used it same-day to build the MAAS ephemeral image — the tool has now replaced its own reason for existing.",
    effortHours: 1,
    source: "manual",
    tags: ["release", "milestone"],
    links: [
      {
        label: "v1.0.0 release",
        url: "https://github.com/grewelltech/iso-kit/releases/tag/v1.0.0",
      },
    ],
  },
  {
    id: "act-160",
    projectId: "iso-kit",
    date: "2026-04-20",
    type: "work",
    title: "Post-1.0 wrap: board archived, project wound down",
    details: "Closed remaining nice-to-have issues as wontfix-for-now, archived the board. Reopen only on a real regression.",
    effortHours: 0.5,
    source: "manual",
    tags: ["wrapup"],
    links: [],
  },

  // ── Planned (tentative future work) ─────────────────────────────────────
  {
    id: "act-161",
    projectId: "loom",
    date: "2026-07-27",
    type: "work",
    title: "Write failing stale-session test; start the fix",
    details:
      "Port scripts/repro-stale-session.sh into TestDeleteUserRevokesSessions, watch it fail, then start the DeleteUser tx cascade.",
    source: "manual",
    tags: ["tests", "sessions"],
    links: [],
    planned: true,
  },
  {
    id: "act-162",
    projectId: "openops",
    date: "2026-07-29",
    type: "meeting",
    title: "Deploy pipeline retro with the team",
    details: "Walk through the runner-02 RCA and the June/July SLO numbers; agree Q3 reliability priorities.",
    source: "manual",
    tags: ["sync"],
    links: [],
    planned: true,
  },
  {
    id: "act-163",
    projectId: "loom",
    date: "2026-07-31",
    type: "milestone",
    title: "Loom v0.9.0 release (target)",
    details: "Go/no-go depends entirely on the stale-session fix landing and soaking in staging.",
    source: "manual",
    tags: ["release"],
    links: [],
    planned: true,
  },
  {
    id: "act-164",
    projectId: "home-infra",
    date: "2026-08-01",
    type: "work",
    title: "Install new PSU in pve-01 and burn-in",
    details: "Swap the bench-tested unit in, return the retired-chassis spare to the shelf, run a few hours of load.",
    source: "manual",
    tags: ["hardware"],
    links: [],
    planned: true,
  },
  {
    id: "act-165",
    projectId: "5g-testbed",
    date: "2026-08-03",
    type: "meeting",
    title: "Licensing kickoff call (if Dan's quote lands)",
    details: "Tentative — only happens if the quote shows up. Agenda: SKU confirmation, delivery timeline, firmware support terms.",
    source: "manual",
    tags: ["vendor", "licensing"],
    links: [],
    planned: true,
  },
  {
    id: "act-166",
    projectId: "openops",
    date: "2026-08-05",
    type: "work",
    title: "Canary stage rollout: top three services",
    details: "Productionize the April canary spike for the three highest-traffic services, behind a per-service flag.",
    source: "manual",
    tags: ["deploy", "canary"],
    links: [],
    planned: true,
  },
  {
    id: "act-167",
    projectId: "loom",
    date: "2026-08-10",
    type: "work",
    title: "Run orphan-session sweep in production",
    details: "Dry-run first, then the real sweep with audit rows. Prod orphan count still unknown — staging had 312.",
    source: "manual",
    tags: ["sessions"],
    links: [],
    planned: true,
  },
  {
    id: "act-168",
    projectId: "ai-research",
    date: "2026-08-12",
    type: "work",
    title: "Prototype MCP server over donezo data",
    details: "Expose projects/activities/notes as MCP resources plus a search tool. Dogfood against the real dataset.",
    source: "manual",
    tags: ["mcp", "prototype"],
    links: [],
    planned: true,
  },
  {
    id: "act-169",
    projectId: "home-infra",
    date: "2026-08-15",
    type: "work",
    title: "Quarterly backup restore drill",
    details: "Full restore of one container and one VM from restic to scratch hardware. Time it; last drill took 47 minutes.",
    source: "manual",
    tags: ["backup", "drill"],
    links: [],
    planned: true,
  },
  {
    id: "act-170",
    projectId: "5g-testbed",
    date: "2026-08-17",
    type: "work",
    title: "Apply RAN550 license; second cell bring-up",
    details: "Contingent on licensing resolving. Activate cell 2, then dry-run the handover rig design from 6/8.",
    source: "manual",
    tags: ["ran550", "handover"],
    links: [],
    planned: true,
  },
];

export const TASKS: TaskItem[] = [
  // open
  {
    id: "task-001",
    projectId: "loom",
    title: "Write failing test: stale sessions after user delete",
    details: "",
    status: "open",
    due: "2026-07-27",
    createdAt: "2026-07-21",
  },
  {
    id: "task-002",
    projectId: "5g-testbed",
    title: "Email Dan about the RAN550 licensing quote",
    details: "",
    status: "open",
    due: "2026-07-28",
    createdAt: "2026-07-20",
  },
  {
    id: "task-003",
    projectId: "loom",
    title: "Cut v0.9.0 final (gated on stale-session fix)",
    details: "",
    status: "open",
    due: "2026-07-31",
    createdAt: "2026-07-17",
  },
  {
    id: "task-004",
    projectId: "home-infra",
    title: "Install replacement PSU in pve-01",
    details: "",
    status: "open",
    due: "2026-08-01",
    createdAt: "2026-07-25",
  },
  {
    id: "task-005",
    projectId: "openops",
    title: "Write runner-02 conntrack RCA doc",
    details: "",
    status: "open",
    due: "2026-08-04",
    createdAt: "2026-07-20",
  },
  {
    id: "task-006",
    projectId: "home-infra",
    title: "Rotate remaining service PATs; add expiry alerts",
    details: "",
    status: "open",
    due: "2026-08-07",
    createdAt: "2026-07-19",
  },
  {
    id: "task-007",
    projectId: "openops",
    title: "Canary-stage rollout plan for top three services",
    details: "",
    status: "open",
    createdAt: "2026-07-16",
  },
  {
    id: "task-008",
    projectId: "loom",
    title: "Productionize orphan-session sweep job",
    details: "",
    status: "open",
    createdAt: "2026-07-23",
  },
  {
    id: "task-009",
    projectId: "ai-research",
    title: "Write up RAG eval results (34/40, multi-hop failures)",
    details: "",
    status: "open",
    createdAt: "2026-07-11",
  },
  {
    id: "task-010",
    projectId: "home-infra",
    title: "Eval MAAS 3.6 — IPMI power-query timeout fix?",
    details: "",
    status: "open",
    createdAt: "2026-06-18",
  },
  {
    id: "task-011",
    title: "Update resume with the 5G lab work",
    details: "",
    status: "open",
    createdAt: "2026-06-30",
  },
  {
    id: "task-012",
    title: "File expense report for the attenuator pads",
    details: "",
    status: "open",
    createdAt: "2026-07-08",
  },
  {
    id: "task-013",
    projectId: "5g-testbed",
    title: "Script SIM provisioning end-to-end (pySim + Open5GS)",
    details: "",
    status: "open",
    createdAt: "2026-06-19",
  },
  {
    id: "task-014",
    projectId: "loom",
    title: "Dashboard panel for session_owner_check hit rate",
    details: "",
    status: "open",
    createdAt: "2026-07-22",
  },
  // waiting
  {
    id: "task-015",
    projectId: "5g-testbed",
    title: "Second cell bring-up on RAN550",
    details: "",
    status: "waiting",
    waitingOn: "Dan (vendor quote)",
    createdAt: "2026-06-12",
  },
  {
    id: "task-016",
    projectId: "openops",
    title: "Open inbound port for deploy webhook",
    details: "",
    status: "waiting",
    waitingOn: "IT — firewall change window",
    createdAt: "2026-07-15",
  },
  {
    id: "task-017",
    projectId: "loom",
    title: "Security review of v0.9 auth changes",
    details: "",
    status: "waiting",
    waitingOn: "Priya (security team)",
    createdAt: "2026-07-17",
  },
  {
    id: "task-018",
    projectId: "5g-testbed",
    title: "Programmable attenuator delivery",
    details: "",
    status: "waiting",
    waitingOn: "RF vendor — backorder ETA",
    createdAt: "2026-05-26",
  },
  {
    id: "task-019",
    projectId: "home-infra",
    title: "Offsite backup box at Dad's place",
    details: "",
    status: "waiting",
    waitingOn: "Dad — shelf space and a network drop",
    createdAt: "2026-05-30",
  },
  // someday
  {
    id: "task-020",
    projectId: "personal-website",
    title: "Finish homelab writeup and relaunch the site",
    details: "",
    status: "someday",
    createdAt: "2026-05-08",
  },
  {
    id: "task-021",
    projectId: "ai-research",
    title: "Fine-tune a small model on my notes style",
    details: "",
    status: "someday",
    createdAt: "2026-04-24",
  },
  {
    id: "task-022",
    projectId: "home-infra",
    title: "IPv6 rollout across all VLANs",
    details: "",
    status: "someday",
    createdAt: "2026-03-21",
  },
  {
    id: "task-023",
    title: "Learn Rust properly (Advent of Code?)",
    details: "",
    status: "someday",
    createdAt: "2026-03-02",
  },
  // done
  {
    id: "task-024",
    projectId: "home-infra",
    title: "Rotate Puppet PAT and store in hiera-eyaml",
    details: "",
    status: "done",
    createdAt: "2026-07-19",
  },
  {
    id: "task-025",
    projectId: "loom",
    title: "Tag v0.9.0-rc1 with known-issues note",
    details: "",
    status: "done",
    createdAt: "2026-07-15",
  },
  {
    id: "task-026",
    projectId: "openops",
    title: "Pull ops-runner-02 from the pool",
    details: "",
    status: "done",
    createdAt: "2026-07-10",
  },
  {
    id: "task-027",
    projectId: "iso-kit",
    title: "Publish 1.0 release notes",
    details: "",
    status: "done",
    createdAt: "2026-04-16",
  },
];

export const NOTES: NoteItem[] = [
  {
    id: "note-001",
    projectId: "home-infra",
    title: "VLAN plan",
    body:
      "VLAN 10 mgmt 10.10.10.0/24 · VLAN 20 trusted 10.10.20.0/24 · VLAN 30 lab 10.10.30.0/24 · VLAN 40 iot 10.10.40.0/24 · VLAN 50 guest 10.10.50.0/24. Trunks: sw-core ports 1-4 (hypervisors, all VLANs), port 12 (office drop, 10/20/30). IoT: internet only. Guest: fully isolated. Lab→mgmt one-way.",
    createdAt: "2026-03-21",
  },
  {
    id: "note-002",
    projectId: "5g-testbed",
    title: "RAN550 rack wiring notes",
    body:
      "ran550-lab in rack U12-13. Mgmt eth0 → sw-core port 18 (VLAN 30, static 10.10.30.55). TX1 → 30dB pad → 30dB pad → UE bench N-panel (measured chain loss 62.4 dB incl. cables). TX2 capped — reserved for cell 2 once licensed. Never power TX uncapped.",
    createdAt: "2026-04-22",
  },
  {
    id: "note-003",
    projectId: "loom",
    title: "Loom session table schema quirks",
    body:
      "sessions.user_id is a plain uuid COPY of users.id — no FK, so nothing cascades on user delete (root of the stale-session bug). Same pattern in api_keys. password_reset_tokens has a real FK with ON DELETE CASCADE. expires_at has a partial index WHERE revoked = false; keep the sweeper's WHERE clause matching or it seq-scans. revoked=true rows are kept 30 days for audit, then swept.",
    createdAt: "2026-07-14",
  },
  {
    id: "note-004",
    projectId: "home-infra",
    title: "Puppet PAT rotation procedure",
    body:
      "1) Generate new fine-grained PAT (repo:read on control-repo, 90-day max). 2) eyaml encrypt -s '<token>' and update r10k::remote key in hiera. 3) Run r10k deploy environment production -pv on puppetserver. 4) puppet agent -t on one host to verify. 5) Update the expiry reminder. Symptom of expiry: agents 401 fetching control repo but the error blames puppetserver.",
    createdAt: "2026-07-19",
  },
  {
    id: "note-005",
    projectId: "openops",
    title: "Runner-02 conntrack RCA notes",
    body:
      "Symptom: intermittent health-gate connect timeouts, only on ops-runner-02, survived image rebuilds. Cause: distro-default nf_conntrack_max while other runners had the tuned sysctl; parallel smoke tests filled the table, kernel dropped packets ('nf_conntrack: table full, dropping packet' in dmesg). Fix: sysctl enforced via config mgmt on all runners 7/21. Detection gap: need per-runner failure-rate alert (agreed at 7/16 retro).",
    createdAt: "2026-07-20",
  },
  {
    id: "note-006",
    projectId: "5g-testbed",
    title: "Open5GS config locations on core-5g",
    body:
      "All configs in /etc/open5gs, tracked in git (~/repos/open5gs-config, deploy.sh rsyncs + restarts). amf.yaml: PLMN 999/70, TAC 1. upf.yaml: N3 MTU fix lives here — do not revert. Subscriber DB via WebUI on :9999 or open5gs-dbctl. Logs: /var/log/open5gs/*.log.",
    createdAt: "2026-04-02",
  },
  {
    id: "note-007",
    projectId: "ai-research",
    title: "sqlite-vec vs Qdrant decision context",
    body:
      "Corpus ≤50k chunks. Measured recall@8 parity between the two on my notes set. sqlite-vec: single file, no daemon, backup = copy the file. Qdrant wins only past ~1M vectors or with multi-user filtering needs. Revisit trigger: corpus 10x or concurrent writers.",
    createdAt: "2026-04-13",
  },
  {
    id: "note-008",
    projectId: "home-infra",
    title: "Backup layout",
    body:
      "restic repo A (local, on lxd-02 zfs dataset): all containers nightly 02:00, 14 daily / 8 weekly / 6 monthly. Repo B (offsite B2): rsynced from A nightly 04:00. VM images: weekly full via snapshot+export. Check cadence: monthly restic check with 10% read-data. Restore drill: quarterly (last: 47 min for container+VM).",
    createdAt: "2026-03-28",
  },
  {
    id: "note-009",
    title: "Go release checklist",
    body:
      "gofmt -w . · golangci-lint run ./... · go test ./... (race on) · CHANGELOG entry · tag vX.Y.Z (annotated) · goreleaser for cross-platform binaries · verify checksums · release notes with upgrade caveats. Used for iso-kit 1.0 and loom releases.",
    createdAt: "2026-04-15",
  },
  {
    id: "note-010",
    title: "Hardware spares inventory",
    body:
      "Shelf B: retired Supermicro chassis (PSU currently ON LOAN to pve-01 since 7/11), 2x 1TB SATA SSD, 1x LSI HBA, assorted N-type adapters and one spare 30dB pad, 3x sysmoISIM blanks, cold-spare 8-port switch. New pve-01 PSU bench-tested 7/25, awaiting install.",
    createdAt: "2026-07-04",
  },
];

export const REMINDERS: Reminder[] = [
  {
    id: "rem-001",
    text: "Email Dan about the RAN550 licensing quote",
    details: "",
    remindAt: "2026-07-28T09:00:00",
    projectId: "5g-testbed",
  },
  {
    id: "rem-002",
    text: "Check LXD snapshot rotation ran clean this week",
    details: "",
    remindAt: "2026-07-26T08:00:00",
    projectId: "home-infra",
  },
  {
    id: "rem-003",
    text: "Confirm PSU delivery before the weekend install",
    details: "",
    remindAt: "2026-07-27T18:00:00",
    projectId: "home-infra",
    done: true,
  },
  {
    id: "rem-004",
    text: "Loom v0.9.0 go/no-go — is the stale-session fix soaked?",
    details: "",
    remindAt: "2026-07-31T10:00:00",
    projectId: "loom",
  },
  {
    id: "rem-005",
    text: "Silenced alerts expire soon — fix thresholds or re-triage",
    details: "",
    remindAt: "2026-08-04T09:00:00",
    projectId: "openops",
  },
  {
    id: "rem-006",
    text: "Verify the Puppet PAT expiry alert actually fires (90-day window)",
    details: "",
    remindAt: "2026-08-10T09:00:00",
    projectId: "home-infra",
  },
];

export const INBOX_ITEMS: InboxItem[] = [
  // pending
  {
    id: "inb-001",
    raw: "Remind me Tuesday morning to email Dan about the RAN550.",
    capturedAt: "2026-07-24T16:42:00",
    suggestedKind: "reminder",
    suggestedProjectId: "5g-testbed",
    status: "pending",
  },
  {
    id: "inb-002",
    raw: "Loom bug: deleting a user leaves stale sessions.",
    capturedAt: "2026-07-20T14:05:00",
    suggestedKind: "task",
    suggestedProjectId: "loom",
    status: "pending",
  },
  {
    id: "inb-003",
    raw: "Spent two hours fixing the Puppet PAT issue.",
    capturedAt: "2026-07-20T08:31:00",
    suggestedKind: "activity",
    suggestedProjectId: "home-infra",
    status: "pending",
  },
  {
    id: "inb-004",
    raw: "That deploy flake was conntrack all along. Write it up properly.",
    capturedAt: "2026-07-20T17:12:00",
    suggestedKind: "task",
    suggestedProjectId: "openops",
    status: "pending",
  },
  {
    id: "inb-005",
    raw: "Check if MAAS 3.6 fixes the IPMI power query timeouts.",
    capturedAt: "2026-07-22T20:14:00",
    suggestedKind: "task",
    suggestedProjectId: "home-infra",
    status: "pending",
  },
  {
    id: "inb-006",
    raw: "Ask Marcus about the thing from Thursday standup.",
    capturedAt: "2026-07-23T10:03:00",
    suggestedKind: "task",
    status: "pending",
  },
  {
    id: "inb-007",
    raw: "Idea: donezo could ingest git commits as activity entries.",
    capturedAt: "2026-07-24T22:37:00",
    suggestedKind: "note",
    suggestedProjectId: "ai-research",
    status: "pending",
  },
  {
    id: "inb-008",
    raw: "srsRAN 25.04 changelog mentions ZMQ timing fixes — check.",
    capturedAt: "2026-07-23T13:48:00",
    suggestedKind: "note",
    suggestedProjectId: "5g-testbed",
    status: "pending",
  },
  {
    id: "inb-009",
    raw: "Grafana disk alert on maas-ctrl fired twice this week. Noise?",
    capturedAt: "2026-07-25T09:20:00",
    suggestedKind: "task",
    suggestedProjectId: "home-infra",
    status: "pending",
  },
  // history
  {
    id: "inb-010",
    raw: "Tag rc1 Friday morning before standup.",
    capturedAt: "2026-07-16T18:20:00",
    suggestedKind: "task",
    suggestedProjectId: "loom",
    status: "converted",
  },
  {
    id: "inb-011",
    raw: "Remind me Saturday to verify the backup restore.",
    capturedAt: "2026-07-16T21:04:00",
    suggestedKind: "reminder",
    suggestedProjectId: "home-infra",
    status: "converted",
  },
  {
    id: "inb-012",
    raw: "Maybe rewrite the website in Astro v6 when it lands?",
    capturedAt: "2026-07-21T23:11:00",
    suggestedKind: "note",
    suggestedProjectId: "personal-website",
    status: "dismissed",
  },
];
